import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Detail/Header";

const Detail: NextPage = () => {
  return (
    <div id="app">
      <Head>
        <title>ncnc-project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>디테일 페이지</h1>
    </div>
  );
};

export default Detail;
